title: Vikraman Senthil Kumar
url: "https://vikramansen.github.io/"
baseurl: "/"


tracking_id: #

footer: no
# footer_url: "https://github.com/ankitsultana"
footer_text: "Page design courtesty of https://github.com/ankitsultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Contact"
   link: "contact"
 - name: "Reading List"
   link: "books"

